package appthemes

func init() {
	Register(&Template{
		Name:        "discord",
		Description: "Discord configuration",
		Content: `
/**
 * @name Heimdall Theme
 * @description Generated by Heimdall CLI
 * @version 1.0.0
 * @author Heimdall
 */

:root {
  --background-primary: {{background}};
  --background-secondary: {{colour0}};
  --background-tertiary: {{colour8}};
  --background-floating: {{background}};
  --background-mobile-primary: {{background}};
  --background-mobile-secondary: {{colour0}};
  --channeltextarea-background: {{colour0}};
  --text-normal: {{foreground}};
  --text-muted: {{colour7}};
  --text-link: {{colour4}};
  --interactive-normal: {{colour7}};
  --interactive-hover: {{foreground}};
  --interactive-active: {{colour15}};
  --interactive-muted: {{colour8}};
  --header-primary: {{foreground}};
  --header-secondary: {{colour7}};
}
`,
	})
}
