package appthemes

import (
	"os"
	"path/filepath"

	"github.com/arthur404dev/heimdall-cli/internal/config"
)

func init() {
	Register(&Template{
		Name:        "nvim",
		Description: "Neovim configuration for Catppuccin theme",
		GetOutputPath: func() string {
			cfg := config.Get()
			if cfg != nil && cfg.Theme.Paths.Nvim != "" {
				return cfg.Theme.Paths.Nvim
			}
			// Default path
			home, _ := os.UserHomeDir()
			return filepath.Join(home, ".config", "nvim", "lua", "user", "heimdall.lua")
		},
		Content: `
-- Heimdall color scheme overrides for Catppuccin
-- Generated by heimdall-cli

local M = {}

-- Define colors table
local colors = {
    -- Base colors 
		base = "{{base}}",
    mantle = "{{mantle}}",
    crust = "{{crust}}",
    
    -- Surface colors
    surface0 = "{{surface0}}",
    surface1 = "{{surface1}}",
    surface2 = "{{surface2}}",
    
    -- Overlay colors
    overlay0 = "{{overlay0}}",
    overlay1 = "{{overlay1}}",
    overlay2 = "{{overlay2}}",
    
    -- Text colors
    text = "{{text}}",
    subtext0 = "{{subtext0}}",
    subtext1 = "{{subtext1}}",
    
    -- Catppuccin palette colors
    rosewater = "{{rosewater}}",
    flamingo = "{{flamingo}}",
    pink = "{{pink}}",
    mauve = "{{mauve}}",
    red = "{{red}}",
    maroon = "{{maroon}}",
    peach = "{{peach}}",
    yellow = "{{yellow}}",
    green = "{{green}}",
    teal = "{{teal}}",
    sky = "{{sky}}",
    sapphire = "{{sapphire}}",
    blue = "{{blue}}",
    lavender = "{{lavender}}",
}

M.color_overrides = {
  all = colors,
}
M.colors = colors

return M
`,
	})
}
